services:
  - type: web
    name: ticket-system
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction
      php artisan config:clear
      php artisan cache:clear
      php artisan migrate --force
      php artisan db:seed --force
      php artisan storage:link
      php artisan optimize
      php artisan view:clear
      php artisan route:clear
    startCommand: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://prueba.gahandi.dev
      - key: APP_KEY
        value: base64:uAQv9VO52+pdwbWclbNPkdH98W7ybQbnerZHBzTubV0=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: apps-web-extra-gsch-69b2.g.aivencloud.com
      - key: DB_PORT
        value: 20606
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_5ers-mFGmvYZyuNz9zT
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: false
      - key: MYSQL_ATTR_SSL_CA
        value: ""
      - key: MYSQL_ATTR_SSL_CIPHER
        value: ""
      - key: REDIS_URL
        fromService:
          type: redis
          name: ticket-redis
          property: connectionString
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: your-email@gmail.com
      - key: MAIL_PASSWORD
        value: your-app-password
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: your-email@gmail.com
      - key: MAIL_FROM_NAME
        value: "Ticket System"

  - type: redis
    name: ticket-redis
    plan: starter
    region: oregon

